services:
  db:
    image: postgres:15
    container_name: smartfarm_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  django:
    build:
      context: ./backend/services/user_management
      dockerfile: Dockerfile
    container_name: smartfarm_django
    restart: unless-stopped
    env_file:
      - ./.env       # ðŸ‘ˆ ÙÙ‚Ø· Ù‡Ù…ÛŒÙ†ØŒ Ø¯ÛŒÚ¯Ø± .env.docker Ù†Ø¯Ø§Ø±ÛŒÙ…
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  fastapi:
    build:
      context: ./backend/services/decision_engine_fastapi
      dockerfile: Dockerfile
    container_name: smartfarm_fastapi
    restart: unless-stopped
    env_file:
      - ./.env       # ðŸ‘ˆ Ù‡Ù…ÛŒÙ†
    depends_on:
      - django
    ports:
      - "9000:9000"
    command: >
      sh -c "uvicorn app.main:app --host ${FASTAPI_HOST:-0.0.0.0} --port ${FASTAPI_PORT:-9000} --reload"

volumes:
  postgres_data:
